### ISSUE TITLE
How to use registerComponents and render them for components under sub folders

### ISSUE THREAD

**Issue by acetinick** [skryukov/turbo-mount#15]
Hey I have components structured into folders and want to use register components to autoload them all.

Recruit
-> Board.vue
-> BoardItem.vue

I can't work out how to render these components

```
<%= turbo_amount("Recruit.Board") %>
<%= turbo_amount("Recruit--Board") %>
<%= turbo_amount("Board") %>
```

all don't work.  I think "Recruit.Board" would be the most ideal

**Comment by skryukov** [comment]
Thanks @acetinick, good catch! I prepared a draft PR #16, will merge and release a fix later today, the resulting interface will (probably) be `<%= turbo_mount("Recruit/Board") %>`.
