### ISSUE TITLE
Cannot get this working (Rails 7.2, yarn, shakapacker)

### ISSUE THREAD

**Issue by sstrudeau** [skryukov/turbo-mount#19]
Hi, I've run into a few issues trying to get this working in a Rails 7.2 app using yarn with Shakapacker.

I've added and installed the gem. When I tried running the installer, I received an error:

```
Installing Turbo Mount
Specify all options when running the generator non-interactively.
```

I added a framework argument (`--framework=react`) since I couldn't figure out how to force it into interactive mode and then it seemed to complete.

I made sure the node module was installed with `yarn add turbo-mount` and confirmed 0.4.0 is installed both in my Gemfile.lock and package.json

When I try to load TurboMount in my app I receive an error (commenting out follow on lines to focus on just loading the module):

`import { TurboMount } from 'turbo-mount';`

When attempting to import TurboMount webpack reports:

`Module not found: Error: Default condition should be last one`

No loading order or method of loading seems to get around this. Any tips on what to try? If this isn't the correct forum for this sort of request, please point me to any appropriate place to ask. Thanks!

**Comment by skryukov** [comment]
Hey @sstrudeau, thanks for the issue!

I pushed the fix for "Specify all options when running the generator non-interactively" to `main`. Will publish a release soon.

Regarding the Shakapacker issue: it can't handle exports for the main file for some reason. Thankfully, you can use this workaround for now:

```diff
- import { TurboMount } from "turbo-mount";
- import { registerComponent } from "turbo-mount/react";
+ import { TurboMount, registerComponent } from "turbo-mount/react";
```

**Comment by skryukov** [comment]
Ok, 15 minutes later I found the root of the problem: our `app/javascript/turbo-mount.js` takes precedence over the library from node modules—webpacker/shakapacker magic in action.

I will prepare an update to the generator to play nicely with shakapacker later this week. For now, you can just rename `app/javascript/turbo-mount.js` to `app/javascript/turbo-mount-initializer.js`.
