### ISSUE TITLE
Handle `data-turbo-permanent`

### ISSUE THREAD

**Issue by phillipspc** [skryukov/turbo-mount#22]
My rails project uses a React component for the top bar. The behavior I want is for this topbar to be considered "permanent" and just have the rest of the page updated on a Turbo visit. You're supposed to get this by using the `data-turbo-permanent` [attribute](https://turbo.hotwired.dev/handbook/page_refreshes#exclude-sections-from-morphing), however turbo-mount does not seem to see/respect this attribute and the component re-renders each time, causing a page flicker.

Are there plans to support this?

**Comment by skryukov** [comment]
Hey @phillipspc, thanks for the issue!

Turbo Mount does support `data-turbo-permanent`, here's an example (note the `id` attribute must be provided):

```erb
<%= turbo_mount("Toolbar", id: "toolbar", 'data-turbo-permanent': true) %>
```

Here's another example—the `player` component is wrapped with a div with the `data-turbo-permanent` attribute.
Wrapper: https://github.com/palkan/turbo-music-drive/blob/demo/turbo-mount/app/views/layouts/application.html.erb#L30-L32
Partial with a Turbo Mount component: https://github.com/palkan/turbo-music-drive/blob/demo/turbo-mount/app/views/player/_player.html.erb

**Comment by phillipspc** [comment]
@skryukov thanks for your reply, this was my mistake. My issue turned out not to be related to `data-turbo-permanent` and instead related to some new behavior after upgrading to React 18.

I’ll close this one now. Cheers!
